---
title: "Problem 2"
author: "Weixin Peng & Lu Gan"
date: "November 14, 2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
```

```{r}
data_nynoaa = read_csv("./data/nynoaadat.csv") %>%
  clean_names() %>%
  filter(id %in% c("USC00300085", "USC00300183", "USC00301152")) %>%
  mutate(ymd = date) %>%
  separate(ymd, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    year = as.integer(year),
    month = as.integer(month),     
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
  ) %>%
  select(id, year, month, tmax, tmin) %>%
  na.omit 
```

Column {.sidebar}
-----------------------------------------------------------------------
This `flexdashboard` with Shiny was made for P8105 Data Scienc course homework 6, problem 2. The data come from [NY NOAA](http://jeffgoldsmith.com/DSI/dataset_noaa.html).

```{r}
station = data_nynoaa %>% distinct(id) %>% pull()
selectInput("station_choice", label = h3("Select station"),
            choices = station, selected = "USC00300085")

renderPrint({ 
  input$station_choice
})

max_year = data_nynoaa %>% distinct(year) %>% max()
min_year = data_nynoaa %>% distinct(year) %>% min()
  
sliderInput("year_range", label = h3("Choose year range"), min = min_year, 
        max = max_year, value = c(1981, 2000))
```


Row
-----------------------------------------------------------------------

### The distribution of mean tmax of each month

```{r}
renderPlotly({
data_nynoaa %>%
  filter(id == input$station_choice,
         year %in% input$year_range[1] : input$year_range[2]) %>% 
  mutate( month = as.factor(month)) %>% 
  group_by(month) %>%
  plot_ly(y = ~tmax, x = ~month, color = ~month, type = "box",
          colors = "Set2")
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

